server:
  port: 8081
spring:
  datasource:
    username: admin
    password: adminPassword
    url: jdbc:postgresql://ms-user-db:5432/ms-user-db
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://sbrotzqy:NueWITpZbDI3sppVS8gquNwlz7xYQFqY@beaver.rmq.cloudamqp.com/sbrotzqy

broker:
  queue:
    email:
      name: default.email