server:
  port: 8081
spring:
  datasource:
    username: adminUser
    password: adminUserPassword
    url: jdbc:postgresql://localhost:5432/ms-db-user
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://sbrotzqy:NueWITpZbDI3sppVS8gquNwlz7xYQFqY@beaver.rmq.cloudamqp.com/sbrotzqy

broker:
  queue:
    email:
      name: default.email