server:
  port: 8082
spring:
  datasource:
    username: adminEmail
    password: adminPassword
    url: jdbc:postgresql://localhost:5432/ms-db-email
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://sbrotzqy:NueWITpZbDI3sppVS8gquNwlz7xYQFqY@beaver.rmq.cloudamqp.com/sbrotzqy

broker:
  queue:
    email:
      name: default.email