server:
  port: 8082
spring:
  datasource:
    username: adminEmail
    password: adminPassword
    url: jdbc:postgresql://localhost:5432/ms-db-email
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: amqps://sbrotzqy:NueWITpZbDI3sppVS8gquNwlz7xYQFqY@beaver.rmq.cloudamqp.com/sbrotzqy
  mail:
    host: smtp.gmail.com
    port: 587
    username: portfolio.allamymp@gmail.com
    password: zckk przo ytta xhhy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
broker:
  queue:
    email:
      name: default.email
